# Generated by Django 3.2.3 on 2023-11-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avdsname', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.BigIntegerField()),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_month', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_year', models.CharField(blank=True, max_length=255, null=True)),
                ('updated', models.BooleanField(blank=True, default=False, null=True)),
                ('random_action', models.IntegerField(blank=True, default=0, null=True)),
                ('engagement', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('LOGIN_ISSUE', 'LOGIN_ISSUE'), ('SUSPENSION', 'SUSPENSION')], default='ACTIVE', max_length=255, null=True)),
                ('following', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('can_search', models.BooleanField(default=True)),
                ('avd_pc', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_filtered', models.BooleanField(default=False)),
                ('bio', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_bio_updated', models.BooleanField(default=False)),
            ],
        ),
    ]
