# Generated by Django 3.2.3 on 2023-11-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('port', models.IntegerField(unique=True)),
                ('proxy_type', models.CharField(blank=True, choices=[('NORD_VPN', 'NordVPN'), ('SURFSHARK', 'SURFSHARK'), ('SMART_PROXY', 'SMART_PROXY'), ('CYBERGHOST', 'CYBERGHOST')], default='CYBERGHOST', max_length=50, null=True)),
                ('country', models.CharField(blank=True, choices=[('Albania', 'Albania'), ('Algeria', 'Algeria'), ('Andorra', 'Andorra'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Bahamas', 'Bahamas'), ('Bangladesh', 'Bangladesh'), ('Belarus', 'Belarus'), ('Belgium', 'Belgium'), ('Bosnia & Herzegovina', 'Bosnia & Herzegovina'), ('Brazil', 'Brazil'), ('Bulgaria', 'Bulgaria'), ('Cambodia', 'Cambodia'), ('Canada', 'Canada'), ('Chile', 'Chile'), ('China', 'China'), ('Colombia', 'Colombia'), ('Costa Rica', 'Costa Rica'), ('Croatia', 'Croatia'), ('Cyprus', 'Cyprus'), ('Czechia', 'Czechia'), ('Denmark', 'Denmark'), ('Egypt', 'Egypt'), ('Estonia', 'Estonia'), ('Finland', 'Finland'), ('France', 'France'), ('Georgia', 'Georgia'), ('Germany', 'Germany'), ('Greece', 'Greece'), ('Greenland', 'Greenland'), ('Hong Kong', 'Hong Kong'), ('Hungary', 'Hungary'), ('Iceland', 'Iceland'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Iran', 'Iran'), ('Ireland', 'Ireland'), ('Isle of Man', 'Isle of Man'), ('Israel', 'Israel'), ('Italy', 'Italy'), ('Japan', 'Japan'), ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Latvia', 'Latvia'), ('Liechtenstein', 'Liechtenstein'), ('Lithuania', 'Lithuania'), ('Luxembourg', 'Luxembourg'), ('Macau', 'Macau'), ('Macedonia (FYROM)', 'Macedonia (FYROM)'), ('Malaysia', 'Malaysia'), ('Malta', 'Malta'), ('Mexico', 'Mexico'), ('Moldova', 'Moldova'), ('Monaco', 'Monaco'), ('Mongolia', 'Mongolia'), ('Montenegro', 'Montenegro'), ('Morocco', 'Morocco'), ('Netherlands', 'Netherlands'), ('New Zealand', 'New Zealand'), ('Nigeria', 'Nigeria'), ('Norway', 'Norway'), ('Pakistan', 'Pakistan'), ('Panama', 'Panama'), ('Philippines', 'Philippines'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('Qatar', 'Qatar'), ('Romania', 'Romania'), ('Russia', 'Russia'), ('Saudi Arabia', 'Saudi Arabia'), ('Serbia', 'Serbia'), ('Singapore', 'Singapore'), ('Slovakia', 'Slovakia'), ('Slovenia', 'Slovenia'), ('South Africa', 'South Africa'), ('South Korea', 'South Korea'), ('Spain', 'Spain'), ('Sri Lanka', 'Sri Lanka'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Taiwan', 'Taiwan'), ('Thailand', 'Thailand'), ('Turkey', 'Turkey'), ('Ukraine', 'Ukraine'), ('United States', 'United States'), ('United Kingdom', 'United Kingdom'), ('Venezuela', 'Venezuela'), ('Vietnam', 'Vietnam')], max_length=40, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('pcname', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
