# Generated by Django 3.2.3 on 2023-12-07 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravd',
            name='instauser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twbot.user_details'),
        ),
    ]
