# Generated by Django 3.2.3 on 2023-12-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twbot', '0003_remove_useravd_instauser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='avdobj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twbot.useravd'),
        ),
    ]
