# Generated by Django 3.2.3 on 2023-12-07 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twbot', '0004_user_details_avdobj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='avdobj',
        ),
    ]
