# Generated by Django 3.2.3 on 2024-01-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twbot', '0002_activeinstausers'),
        ('twbot', '0004_postdetails_saved_users'),
    ]

    operations = [
    ]
