# Generated by Django 3.2.3 on 2024-01-28 12:44

from django.db import migrations


class Migration(migrations.Migration):
    
    dependencies = [
        ('twbot', '0005_merge_20240128_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveInstaUsers',
        ),
    ]
