# Generated by Django 3.2.3 on 2024-01-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twbot', '0007_run_command'),
    ]

    operations = [
        migrations.DeleteModel(
            name='run_command',
        ),
    ]
