# Generated by Django 3.2.3 on 2024-01-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twbot', '0008_delete_run_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='run_command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('command', models.TextField(default='')),
                ('pcs_name', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
