# Generated by Django 3.2.3 on 2023-06-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='postdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=10000)),
                ('like', models.IntegerField()),
                ('target_comment', models.IntegerField(default=0)),
                ('comment', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
