# Generated by Django 3.2.3 on 2023-07-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twbot', '0002_postdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetails',
            name='commented_users',
            field=models.ManyToManyField(related_name='commented_posts', to='twbot.User_details'),
        ),
        migrations.AddField(
            model_name='postdetails',
            name='shared_users',
            field=models.ManyToManyField(related_name='shared_posts', to='twbot.User_details'),
        ),
        migrations.AddField(
            model_name='postdetails',
            name='target_like',
            field=models.IntegerField(default=0),
        ),
    ]
