# Generated by Django 4.2.7 on 2023-11-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_remove_postdetails_commented_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravd',
            name='pcname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
