# Generated by Django 3.2.3 on 2023-11-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_useravd_pcname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
