# Generated by Django 3.2.3 on 2023-11-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20231127_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='postdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=10000)),
                ('like', models.IntegerField()),
                ('target_comment', models.IntegerField(default=0)),
                ('target_like', models.IntegerField(default=0)),
                ('comment', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('commented_users', models.ManyToManyField(related_name='commented_posts', to='insta.User_details')),
                ('shared_users', models.ManyToManyField(related_name='shared_posts', to='insta.User_details')),
            ],
        ),
    ]
