# Generated by Django 3.2.3 on 2023-11-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_postdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('NONE', 'NONE')], default='NONE', max_length=255, null=True),
        ),
    ]
