# Generated by Django 3.2.3 on 2023-12-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_user_details_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
